<?php

return [
    'jobs' => [
        [
            'id' => 1,
            'title' => 'Technical Support Representative',
            'company' => 'Accenture Philippines',
            'description' => 'Provide first-line technical assistance to clients via phone, chat, and email. Troubleshoot software and hardware issues and escalate complex cases when needed.',
            'location' => 'Mandaluyong City',
            'salary_min' => 22000,
            'salary_max' => 28000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 2,
            'title' => 'Quality Assurance Specialist',
            'company' => 'Unilab, Inc.',
            'description' => 'Inspect and test pharmaceutical products to ensure compliance with quality standards. Document findings and coordinate with production teams on corrective actions.',
            'location' => 'Mandaluyong City',
            'salary_min' => 25000,
            'salary_max' => 32000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 3,
            'title' => 'Accountant',
            'company' => 'San Miguel Corporation',
            'description' => 'Prepare financial statements, manage accounts payable and receivable, and assist with month-end closing. CPA license or eligibility preferred.',
            'location' => 'Mandaluyong City',
            'salary_min' => 30000,
            'salary_max' => 38000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 4,
            'title' => 'Office Administrative Assistant',
            'company' => 'Local Gov Unit (LGU)',
            'description' => 'Support daily office operations including document filing, appointment scheduling, and front-desk reception. Familiarity with LGU procedures is a plus.',
            'location' => 'Pasig City',
            'salary_min' => 16000,
            'salary_max' => 20000,
            'type' => 'Contract',
            'type_key' => 'contract',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 5,
            'title' => 'Software Engineer (React)',
            'company' => 'GCash (Mynt)',
            'description' => 'Build and maintain front-end features for a high-traffic fintech platform using React and TypeScript. Collaborate with designers and backend engineers in an agile team.',
            'location' => 'Taguig City',
            'salary_min' => 45000,
            'salary_max' => 65000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 6,
            'title' => 'Registered Nurse',
            'company' => 'The Medical City',
            'description' => 'Deliver patient care in a hospital ward setting, monitor vital signs, administer medications, and coordinate with physicians on treatment plans.',
            'location' => 'Pasig City',
            'salary_min' => 28000,
            'salary_max' => 35000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 2,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 7,
            'title' => 'Administrative Assistant II',
            'company' => 'Department of Social Welfare and Development (DSWD) NCR',
            'description' => 'Process social welfare program documents, assist beneficiaries at the service window, and maintain accurate records in compliance with government regulations.',
            'location' => 'Manila City, Metro Manila',
            'salary_min' => 27000,
            'salary_max' => 31000,
            'type' => 'Part-Time',
            'type_key' => 'part-time',
            'posted_days_ago' => 2,
            'bookmarked' => true,
            'peso_verified' => true,
        ],
        [
            'id' => 8,
            'title' => 'Customer Service Representative - Healthcare Account',
            'company' => 'Teleperformance Philippines (PESO Verified)',
            'description' => 'Handle inbound calls for a US healthcare client, verify member information, and resolve billing or coverage inquiries with empathy and accuracy.',
            'location' => 'Pasay City, Metro Manila',
            'salary_min' => 24000,
            'salary_max' => 28000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 3,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 9,
            'title' => 'Civil Engineer (Project-Based, City Engineering)',
            'company' => 'Local Government Unit of Quezon City',
            'description' => 'Supervise infrastructure projects such as road repairs and drainage improvements. Review plans, conduct site inspections, and prepare progress reports for the city engineering office.',
            'location' => 'Quezon City, Metro Manila',
            'salary_min' => 35000,
            'salary_max' => 42000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 4,
            'bookmarked' => false,
            'peso_verified' => true,
        ],
        [
            'id' => 10,
            'title' => 'Technical Support Associate I',
            'company' => 'Concentrix Philippines (PESO Partner)',
            'description' => 'Assist customers with device setup, connectivity issues, and account troubleshooting. Strong communication skills and willingness to work shifting schedules required.',
            'location' => 'Taguig City, Metro Manila',
            'salary_min' => 26000,
            'salary_max' => 30000,
            'type' => 'Full-Time',
            'type_key' => 'full-time',
            'posted_days_ago' => 5,
            'bookmarked' => true,
            'peso_verified' => true,
        ],
    ],

    'announcements' => [
        [
            'slug' => 'national-peso-job-fair-2026',
            'day' => '20',
            'month' => 'OCT',
            'category' => 'Job Fair Advisory',
            'category_landing' => 'PESO LGU Update',
            'title' => 'National PESO Job Fair Caravan 2026',
            'excerpt' => 'Join over 100+ local government accredited employers offering fast-track hiring at the SM Mega Trade Hall.',
            'excerpt_full' => 'Join over 100+ accredited employers at the SM Mega Trade Hall on October 20. Free pre-registration is open for verified job seekers. Bring required documents for faster processing.',
            'author' => 'Admin Maria Santos',
            'date' => 'Oct 20, 2026',
            'action_route' => 'enlistment',
            'action_label' => 'Pre-Register Now',
        ],
        [
            'slug' => 'ftjs-ra-11261-guidelines',
            'day' => '15',
            'month' => 'OCT',
            'category' => 'LGU Announcement',
            'category_landing' => 'PESO LGU Update',
            'title' => 'First-Time Jobseeker Bill Implementation Guidelines',
            'title_full' => 'First-Time Jobseeker Bill Implementation Guidelines (RA 11261)',
            'excerpt' => 'LGU announcements concerning simplified requirements to avail of completely free barangay/NBI clearance services.',
            'excerpt_full' => 'The First-Time Job Seeker certification offers free barangay and NBI clearance services. Eligible residents can apply through their local PESO office with required documents. Processing typically takes 1-3 working days.',
            'author' => 'Director Manuel',
            'date' => 'Oct 15, 2026',
            'action_route' => 'first-time-job-seeker',
            'action_label' => 'Apply for Certification',
        ],
        [
            'slug' => 'digital-skills-training',
            'day' => '08',
            'month' => 'OCT',
            'category' => 'Skills & Training',
            'category_landing' => 'PESO LGU Update',
            'title' => 'Free Digital Skills Training & Upskilling',
            'title_full' => 'Free Digital Skills Training & Upskilling Caravan',
            'excerpt' => 'PESO in collaboration with DICT introduces micro-credentialing courses for administrative and development jobs.',
            'excerpt_full' => 'PESO and DICT are offering free digital skills training with micro-credentialing. Tracks include Digital Literacy, Customer Service, and Web Development. Slots are limited and registration is now open.',
            'author' => 'Coop Officer Jane Diaz',
            'date' => 'Oct 08, 2026',
            'action_route' => 'enlistment',
            'action_label' => 'Register for Training',
        ],
    ],

    'referral_job_options' => [
        'Administrative Assistant II',
        'Customer Service Representative - Healthcare Account',
        'Civil Engineer (Project-Based, City Engineering)',
        'Technical Support Associate I',
        'Software Engineer (React)',
        'Registered Nurse',
    ],
];
